# Generated by Django 2.2 on 2019-05-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('programa', models.CharField(max_length=100)),
                ('fechaGrado', models.DateField()),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('union_libre', 'Unión Libre'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=12, null=True)),
                ('direccionResidencia', models.CharField(blank=True, max_length=80, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(blank=True, max_length=40, null=True)),
                ('telefonoFijo', models.CharField(blank=True, max_length=12, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email1', models.EmailField(blank=True, max_length=150, null=True)),
                ('email2', models.EmailField(blank=True, max_length=150, null=True)),
                ('situacion_laboral_actual', models.CharField(blank=True, choices=[('empleado', 'Empleado'), ('desempleado', 'Desempleado'), ('profesionalOConsultorIndependiente', 'Profesional o consultor independiente'), ('Emprendedor_Empresario', 'Emprendedor/empresario'), ('jubilado', 'Jubilado')], max_length=34, null=True)),
                ('experiencia_laboral', models.CharField(blank=True, choices=[('menos_de_1_anio', 'Inferior a un año'), ('1-3_anios', 'Entre 1 y 3 años'), ('4-6_anios', 'Entre 4 y 6 años'), ('7-10_anios', 'Entre 7 y 10 años'), ('11-15_anios', 'Entre 11 y 15 años'), ('16-20_anios', 'Entre 16 y 20 años'), ('mas_de_20_anios', 'Más de 20 años')], max_length=50, null=True)),
                ('nombreEmpresaTrabajoActual', models.CharField(blank=True, max_length=100, null=True)),
                ('sectorDeLaEmpresa', models.CharField(blank=True, choices=[('agropecuario', 'Agropecuario'), ('alimentos', 'Alimentos'), ('asegurador', 'Asegurador'), ('bebidasYTabaco', 'Bebidas y tabaco'), ('comercial', 'Comercial'), ('comunicaciones', 'Comunicaciones'), ('contruccionYObra', 'Construcción y obra'), ('consultoriaAsesoria', 'Consultorías y asesorías'), ('consumoMasivo', 'Consumo masivo'), ('educativo', 'Educativo'), ('energetico', 'Energético'), ('entretenimiento', 'Entretenimineto'), ('estatalYRelacionados', 'Estatal y relacionados'), ('financiero', 'Financiero'), ('industrial', 'Industrial'), ('investigador', 'Investigador'), ('manufactura', 'Manufactura'), ('mediaAmbiente', 'Medio ambiente'), ('medios', 'Medios'), ('mineriaYOtrosMateriales', 'Minería y otros materiales'), ('publicidadYMercadeo', 'Publicidad y mercadeo'), ('salud', 'Salud'), ('servicios', 'Servicios'), ('solidario', 'Solidario'), ('tecnologia', 'Técnologia'), ('telecomunicaciones', 'Telecomunicaciones'), ('textilesPrendasVestirYCalzado', 'Textiles, prendas de vestir y calzado'), ('transporte', 'Transporte'), ('turismo', 'Turismo'), ('vehiculosYPartes', 'Vehículos y partes'), ('vehiculosYPartes', 'Otros')], max_length=50, null=True)),
                ('areaDeTrabajo', models.CharField(blank=True, choices=[('administrativaYFinanciera', 'Administrativa y financiera'), ('agronomia', 'Agronomía'), ('audioVideoIndustrialMusical', 'Audio y video/industria musical'), ('auditoriaContraloriaInterventoria', 'Auditoria/contraloría/interventoría'), ('calidad', 'Calidad (aseguramiento, gestión y afines)'), ('capacitacion', 'Capacitación'), ('carteraFacturacion', 'Cartera/facturación'), ('comercioExteriorOLogisticaInternacional', 'Comercio exterior/logística internacional'), ('compras', 'Compras'), ('comunicacion', 'Comunicación'), ('construiccionYObra', 'Construcción y obra'), ('consultoria', 'Consultoria'), ('contabilidad', 'Contabilidad'), ('costosYPresupuestos', 'Costos y presupuestos'), ('creditoYCobranza', 'Crédito y cobranza'), ('desarrolloProductivo', 'Desarrollo productivo'), ('desarrolloSocialInclusion', 'Desarrollo social/inclusión'), ('direccionGeneral_generalPresidencia', 'Dirección/gerencia general/presidencia'), ('disenioYPublicidad', 'Diseño y publicidad'), ('educacion', 'Educación'), ('facturacion', 'Facturación'), ('financiera', 'Financiera'), ('hoteleriaYTurismo', 'Hotelería y turismo'), ('interventoria', 'Interventoría'), ('investigacion', 'Investigación'), ('juridica', 'Jurídica'), ('logicaYDistribucion', 'Logística y distribución'), ('mantenimiento', 'Mantenimiento'), ('medioAmbienteYRecursosNaturales', 'Medio ambiente y recursos naturales'), ('mediosDigitales', 'Medios digitales'), ('movilidadYEspacioPublico', 'Movilidad y espacio público'), ('mercadeoYPublicidad', 'Mercadeo y publicidad'), ('operacionesYProcesos', 'Operaciones y procesos'), ('planeacionYProyectos', 'Planeación y proyectos'), ('produccionPlataCalidad', 'Producción, planta y calidad'), ('proyectos', 'Proyectos (análisis, desarrollo, gestión y afines)'), ('psicologia', 'Psicología'), ('recreacionYDeporte', 'Recreación y deporte'), ('recursos_humanos_administracion_personal', 'Recursos humanos y administración de personal'), ('relaciones_publica_eventos', 'Relaciones públicas, eventos'), ('salud_o_salud_ocupacional', 'Salud/salud ocupacional'), ('seguridad_industrial_y_riesgos', 'Seguridad industrial y riesgos'), ('servicioAlCliente', 'Servicio al cliente'), ('sistemasDeSonido', 'Sistemas de sonido'), ('sistemasElectricos', 'Sistemas eléctricos'), ('tecnologia', 'Tecnología'), ('tesoreria', 'Tesorería'), ('trabajoSocial', 'Trabajo social'), ('ventas', 'Ventas'), ('', 'Otro')], max_length=50, null=True)),
                ('cargoQueOcupa', models.CharField(blank=True, choices=[('abogado', 'Abogado'), ('administrados', 'Administrador'), ('analista', 'Analista'), ('arquitecto', 'Arquitecto'), ('asesor', 'Asesor'), ('asistente', 'Asistente'), ('auditos', 'Auditor'), ('auxiliar', 'Auxiliar'), ('cajero', 'Cajero'), ('capacitados', 'Capacitador'), ('consultor', 'Consultor'), ('contador', 'Contador'), ('contralor', 'Contralor'), ('coordinador', 'Coordinador'), ('decano', 'Decano'), ('dibujante', 'Dibujante'), ('director', 'Director'), ('diseniador', 'Diseñador'), ('docente', 'Docente'), ('ejecutivo', 'Ejecutivo'), ('entrenador', 'Entrenador'), ('especialista', 'Especialista'), ('gerenteOPresidente', 'Gerente/presidente'), ('ingeniero', 'Ingeniero'), ('instructor', 'Instructor'), ('investigador', 'Investigador'), ('jefe', 'Jefe'), ('negociador', 'Negociador'), ('notario', 'Notario'), ('productor', 'Productor'), ('profesional', 'Profesional'), ('programador', 'Programador'), ('propietario', 'Propietario'), ('psicologo', 'Psicólogo'), ('rector', 'Rector'), ('revisor', 'Revisor'), ('secretario', 'Secretario'), ('subdirector', 'Subdirector'), ('subgerente', 'Subgerente'), ('supervisor', 'Supervisor'), ('vicepresidente', 'Vicepresidente'), ('vicerrector', 'Vicerrector'), ('otro', 'Otro')], max_length=50, null=True)),
                ('nombreJefeInmediato', models.CharField(blank=True, max_length=100, null=True)),
                ('areaTrabajoAfinConSuProfesion', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('tipoDeContrato', models.CharField(blank=True, choices=[('terminoFijo', 'Término fijo'), ('terminoIndefinido', 'Término indefinido'), ('prestacionDeServicio', 'Prestación de servicios'), ('obraLabor', 'Por obra o labor')], max_length=50, null=True)),
                ('rangoSalarial', models.CharField(blank=True, choices=[('Menos de $1.500.000', 'Menos de $1.500.000'), ('$1.500.000 a $2.000.000', '$1.500.000 a $2.000.000'), ('$2.000.000 a $2.500.000', '$2.000.000 a $2.500.000'), ('$2.500.000 a $3.000.000', '$2.500.000 a $3.000.000'), ('$3.000.000 a $3.500.000', '$3.000.000 a $3.500.000'), ('$3.500.000 a $4.000.000', '$3.500.000 a $4.000.000'), ('$4.000.000 a $4.500.000', '$4.000.000 a $4.500.000'), ('$4.500.000 a $5.000.000', '$4.500.000 a $5.000.000'), ('$5.000.000 a $5.500.000', '$5.000.000 a $5.500.000'), ('$5.500.000 a $6.000.000', '$5.500.000 a $6.000.000'), ('$6.000.000 a $8.000.000', '$6.000.000 a $8.000.000'), ('Más de $8.000.000', 'Más de $8.000.000')], max_length=26, null=True)),
                ('participacionActividadesUnimar', models.CharField(blank=True, choices=[('frecuentemente', 'Frecuentemente'), ('regularmente', 'Regularmente'), ('eventualmente', 'Eventualmente'), ('nunca', 'Nunca'), ('otro', 'Otro')], max_length=20, null=True)),
                ('serviciosDeInteres', models.CharField(blank=True, choices=[('programasEducacionContinua', 'Programas de educación continua'), ('programasPosgrados', 'Programas de posgrados'), ('actualizacinProfesional', 'Conferencias de actualización profesional'), ('bolsaEmpleoInstitucional', 'Bolsa de empleo institucional'), ('libreria', 'Librería'), ('biblioteca', 'Biblioteca'), ('escenariosDeportivos', 'Escenarios deportivos'), ('ProgramasDeBienestaInstitucional', 'Programas de bienestar institucional'), ('ninguno', 'Ninguno'), ('otro', 'Otro')], max_length=40, null=True)),
                ('procesoDeInformacionUnimar', models.CharField(blank=True, choices=[('muySatifecho', 'Muy satisfactorio'), ('satisfecho', 'Satisfactorio'), ('pocoSatisfecho', 'Poco Satisfactorio')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=200)),
                ('anio', models.DateField()),
                ('ambito', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=20, null=True)),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_publicacion', models.CharField(max_length=100)),
                ('anio', models.DateField()),
                ('tipo_publicacion', models.CharField(blank=True, choices=[('articulo', 'Artículo'), ('libro', 'Libro'), ('capitoDeLibro', 'Capítulo de libro'), ('documentoResultadoDeInvestigacion', 'Documento resultado de investigación'), ('otro', 'Otro')], max_length=20, null=True)),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeComunidad', models.CharField(blank=True, choices=[('academica', 'Académica'), ('profesional', 'Profesional'), ('cientifica', 'Científica'), ('artistica_cultural', 'Artística / cultural'), ('deportiva', 'Deportiva'), ('otra', 'Otra')], max_length=20, null=True)),
                ('nombreDeLaComunidad', models.CharField(blank=True, max_length=100, null=True)),
                ('ambito', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=20, null=True)),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educacion_formal', models.CharField(blank=True, choices=[('pregrado', 'Pregrado'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=16, null=True)),
                ('titulo_obtenido', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=200)),
                ('anioGraduacion', models.DateField()),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Persona')),
            ],
        ),
    ]
