# Generated by Django 2.2.3 on 2019-08-26 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('identificacion', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=51)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('programa', models.CharField(max_length=100)),
                ('fechaGrado', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Unión Libre', 'Unión Libre'), ('Divorciado(a)', 'Divorciado(a)'), ('Viudo(a)', 'Viudo(a)')], max_length=20, null=True)),
                ('direccionResidencia', models.CharField(blank=True, max_length=80, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonoFijo', models.CharField(blank=True, max_length=12, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email1', models.EmailField(blank=True, max_length=150, null=True)),
                ('email2', models.EmailField(blank=True, max_length=150, null=True)),
                ('situacion_laboral_actual', models.CharField(blank=True, choices=[('Estudiante', 'Estudiante'), ('Empleado', 'Empleado'), ('Desempleado', 'Desempleado'), ('Profesional o consultor independiente', 'Profesional o consultor independiente'), ('Emprendedor/empresario', 'Emprendedor/empresario'), ('Jubilado', 'Jubilado')], max_length=100, null=True)),
                ('experiencia_laboral', models.CharField(blank=True, choices=[('Inferior a un año', 'Inferior a un año'), ('Entre 1 y 3 años', 'Entre 1 y 3 años'), ('Entre 4 y 6 años', 'Entre 4 y 6 años'), ('Entre 7 y 10 años', 'Entre 7 y 10 años'), ('Entre 11 y 15 años', 'Entre 11 y 15 años'), ('Entre 16 y 20 años', 'Entre 16 y 20 años'), ('Más de 20 años', 'Más de 20 años')], max_length=60, null=True)),
                ('participacionActividadesUnimar', models.CharField(blank=True, choices=[('Frecuentemente', 'Frecuentemente'), ('Regularmente', 'Regularmente'), ('Eventualmente', 'Eventualmente'), ('Nunca', 'Nunca')], max_length=100, null=True)),
                ('serviciosDeInteres', models.CharField(blank=True, max_length=41, null=True)),
                ('procesoDeInformacionUnimar', models.CharField(blank=True, choices=[('Muy satisfactorio', 'Muy satisfactorio'), ('Satisfactorio', 'Satisfactorio'), ('Poco Satisfactorio', 'Poco Satisfactorio')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido_reconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('institucionReconocimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('anioReconocimiento', models.DateField(blank=True, null=True)),
                ('ambito', models.CharField(blank=True, choices=[('Local', 'Local'), ('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional'), ('Otra', 'Otra')], max_length=100, null=True)),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_publicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.DateField(blank=True, null=True)),
                ('tipo_publicacion', models.CharField(blank=True, choices=[('Artículo', 'Artículo'), ('Libro', 'Libro'), ('Revista', 'Revista'), ('Capítulo de libro', 'Capítulo de libro'), ('Documento resultado de investigación', 'Documento resultado de investigación'), ('Otra', 'Otra')], max_length=100, null=True)),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeComunidad', models.CharField(blank=True, choices=[('Académica', 'Académica'), ('Profesional', 'Profesional'), ('Científica', 'Científica'), ('Artística / cultural', 'Artística / cultural'), ('Deportiva', 'Deportiva'), ('Otra', 'Otra')], max_length=100, null=True)),
                ('nombreDeLaComunidad', models.CharField(blank=True, max_length=100, null=True)),
                ('ambitoParticipacion', models.CharField(blank=True, choices=[('Local', 'Local'), ('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional'), ('Otra', 'Otra')], max_length=100, null=True)),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='InfoLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('nombreEmpresaTrabajoActual', models.CharField(blank=True, max_length=100, null=True)),
                ('sectorDeLaEmpresa', models.CharField(blank=True, max_length=100, null=True)),
                ('areaDeTrabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('cargoQueOcupa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreJefeInmediato', models.CharField(blank=True, max_length=100, null=True)),
                ('areaTrabajoAfinConSuProfesion', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('tipoDeContrato', models.CharField(blank=True, choices=[('Término fijo', 'Término fijo'), ('Término indefinido', 'Término indefinido'), ('Prestación de servicios', 'Prestación de servicios'), ('Por obra o labor', 'Por obra o labor')], max_length=100, null=True)),
                ('rangoSalarial', models.CharField(blank=True, choices=[('Menos de $1.500.000', 'Menos de $1.500.000'), ('$1.500.000 a $2.000.000', '$1.500.000 a $2.000.000'), ('$2.000.000 a $2.500.000', '$2.000.000 a $2.500.000'), ('$2.500.000 a $3.000.000', '$2.500.000 a $3.000.000'), ('$3.000.000 a $3.500.000', '$3.000.000 a $3.500.000'), ('$3.500.000 a $4.000.000', '$3.500.000 a $4.000.000'), ('$4.000.000 a $4.500.000', '$4.000.000 a $4.500.000'), ('$4.500.000 a $5.000.000', '$4.500.000 a $5.000.000'), ('$5.000.000 a $5.500.000', '$5.000.000 a $5.500.000'), ('$5.500.000 a $6.000.000', '$5.500.000 a $6.000.000'), ('$6.000.000 a $8.000.000', '$6.000.000 a $8.000.000'), ('Más de $8.000.000', 'Más de $8.000.000')], max_length=100, null=True)),
                ('checkTrabajoActual', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educacion_formal', models.CharField(blank=True, choices=[('Pregrado', 'Pregrado'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=100, null=True)),
                ('titulo_obtenido', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('anioGraduacion', models.PositiveIntegerField(max_length=4, validators=[django.core.validators.MinValueValidator(1939), django.core.validators.MaxValueValidator(2019)])),
                ('persona_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Egresado')),
            ],
        ),
    ]
