# Generated by Django 2.2.3 on 2019-08-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='serviciosDeInteres',
            field=models.CharField(blank=True, max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='infolaboral',
            name='areaDeTrabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='infolaboral',
            name='cargoQueOcupa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='infolaboral',
            name='sectorDeLaEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
